---
- name: Create aws ec2 nginx server
  hosts: localhost
  become: false
  gather_facts: false
  vars_prompt:
    - name: "instanceName"
      prompt: "Enter the name for the instance"
      private: no
  tasks:
    - name: Create ec2 instance
      ec2:
        key_name: default-website
        profile: production
        group:
          - website-api-sg
          - build-travisci-sg
          - user-jreardon-sg
        instance_type: t2.micro
        image: ami-04f6fc7f
        vpc_subnet_id: subnet-533c2215
        region: us-east-1
        assign_public_ip: yes
        instance_profile_name: codedeploy-role
        instance_tags:
          Name: "{{ instanceName }}"
          serverType: "nginx"
        wait: true
        count: 1
      register: result
    - name: Add Name tag to the new instance(s)
      ec2_tag:
        region: "{{ item.region }}"
        resource: "{{ item.id }}"
        tags:
          Name: "{{ instanceName }}"
          serverType: "nginx"
      with_items:
        - "{{ result.instances }}"
    - name: Debug output of results
      debug:
        var: result.instances
    - name: Add instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: instances
      with_items:
        - "{{ result.instances }}"
    - name: Wait for SSH
      wait_for:
        host: "{{ item.private_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items:
        - "{{ result.instances }}"
    - name: Copy SSH Key to server
      copy:
        src: site_deploy_rsa.pub
        dest: ~/.ssh/site_deploy_rsa.pub
        mode: 0600
    - name: Deploy SSH key for site deploy
      authorized_key:
        key: "{{ lookup('file', '/home/ec2-user/.ssh/site_deploy_rsa.pub') }}"
        user: ec2-user
        state: present
#    - name: deploy SSH key for site deploy
#      command: "ssh-copy-id -i site_deploy_rsa.pub {{ item.private_dns_name }}"
#      with_items:
#        - "{{ result.instances }}"

- name: Setup NGINX
  hosts: instances
  become: false
  gather_facts: false
  tasks:
    - include: setup-nginx.yml
