---
- name: Start aws ec2 server
  become: false
  gather_facts: false
  hosts: localhost
  vars_prompt:
    - name: "hostName"
      prompt: "Enter the name of the instance"
      private: no
  tasks:
    - include: ec2-instance-discover.yml
    - name: Start server instance
      ec2:
        region: "{{ item.region }}"
        instance_ids: "{{ item.id }}"
        state: running
      with_items:
        - "{{ instances }}"
