---
- name: Get aws ec2 information
  become: false
  gather_facts: false
  hosts: localhost
  vars_prompt:
    - name: "hostName"
      prompt: "Enter the name of the instance"
      private: no
  tasks:
    - include: ec2-variables.yml
    - name: Gather facts
      ec2_remote_facts:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ hostName }}"
      register: result
    - name: Print server instances
      debug:
        var: result.instances
