---
- name: Discover instances(s)
  become: false
  gather_facts: false
  hosts: localhost
  vars_prompt:
    - name: "hostName"
      prompt: "Enter the name of the instance"
      private: no
    - name: "baseDomain"
      prompt: "Enter the root site name"
      private: no
    - name: "siteAliases"
      prompt: "Enter site domain aliases separated with spaces (e.g www.example.com www2.example.com)"
      default: ""
      private: no
    - name: "certPrvKey"
      prompt: "Enter the local (.key) filename for the SSL Cert (if it has one)"
      default: ""
      private: no
    - name: "certPemKey"
      prompt: "Enter the local (.pem/.crt) filename for the SSL Cert (if it has one)"
      default: ""
      private: no
    - name: "certCABundle"
      prompt: "Enter the local (.ca-bundle) filename for the SSL Cert (if it has one)"
      default: ""
      private: no
  tasks:
    - include: ec2-instance-discover.yml
    - name: Add serverType tag to the new instance(s)
      ec2_tag:
        region: "{{ item.region }}"
        resource: "{{ item.id }}"
        tags:
          serverType: "elasticsearch"
      with_items:
        - "{{ result.instances }}"
    - name: set local variables
      set_fact:
        baseDomain: "{{baseDomain}}"
        siteAliases: "{{siteAliases}}"
        certPrvKey: "{{certPrvKey}}"
        certPemKey: "{{certPemKey}}"
        certCABundle: "{{certCABundle}}"
    - name: set default value for sslIncluded
      set_fact:
        sslIncluded: false
    - name: set value for sslIncluded if true
      set_fact:
        sslIncluded: true
      when:
        - certPrvKey|default("") != ""
        - certPemKey|default("") != ""
    - name: set default value for caBundleIncluded
      set_fact:
        caBundleIncluded: false        
    - name: set value for caBundleIncluded if true
      set_fact:
        caBundleIncluded: true
      when:
        - certCABundle|default("") != ""

- name: Setup ELK
  hosts: instances
  become: false
  gather_facts: false
  vars:
    certPrvKey: "{{hostvars['localhost']['certPrvKey']}}"
    certPemKey: "{{hostvars['localhost']['certPemKey']}}"
    certCABundle: "{{hostvars['localhost']['certCABundle']}}"
    caBundleIncluded: "{{hostvars['localhost']['caBundleIncluded']}}"
    hasSSL: "{{hostvars['localhost']['sslIncluded']}}"
    Domain: "{{hostvars['localhost']['baseDomain']}}"
    Aliases: "{{hostvars['localhost']['siteAliases']}}"
  tasks:
    - include: nginx-setup.yml
    - include: esk-setup.yml
    - include: esk-nginx-setup.yml
