---
- name: Discover instances(s)
  become: false
  gather_facts: false
  hosts: localhost
  vars_prompt:
    - name: "hostName"
      prompt: "Enter the name of the instance"
      private: no
  tasks:
    - include: ec2-instance-discover.yml

- name: Setup iptables
  hosts: instances
  become: false
  gather_facts: false
  tasks:
    - include: iptables-setup.yml
