---
- name: Discover instances(s)
  become: false
  gather_facts: false
  hosts: localhost
  vars_prompt:
    - name: "hostName"
      prompt: "Enter the name of the instance"
      private: no
    - name: "influxUser"
      prompt: "Enter the influx admin user name"
      private: no
    - name: "influxPass"
      prompt: "Enter the influx admin password"
      private: no
    - name: "telegraf"
      prompt: "Enter the telegraf password"
      private: no
    - name: "grafana"
      prompt: "Enter the grafana password"
      private: no
  tasks:
    - include: ec2-instance-discover.yml

- name: Setup monitor
  hosts: instances
  become: false
  gather_facts: false
  vars:
    AdminUser: "{{hostvars['localhost']['influxUser']}}"
    AdminPass: "{{hostvars['localhost']['influxPass']}}"
    TelegrafUserPass: "{{hostvars['localhost']['telegraf']}}"
    GrafanaUserPass: "{{hostvars['localhost']['grafana']}}"
  tasks:
    - include: monitor-setup.yml
