---
- name: Create aws ec2 monitor server
  hosts: localhost
  become: false
  gather_facts: false
  vars_prompt:
    - name: "instanceName"
      prompt: "Enter the name for the instance"
      private: no
    - name: "influxUser"
      prompt: "Enter the influx admin user name"
      private: no
    - name: "influxPass"
      prompt: "Enter the influx admin password"
      private: no
    - name: "telegrafPass"
      prompt: "Enter the telegraf password"
      private: no
    - name: "grafanaPass"
      prompt: "Enter the grafana password"
      private: no
  vars:
    ec2size: t2.small
  tasks:
    - include: ec2-instance-create.yml

- name: Setup Monitoring Software
  hosts: instances
  become: false
  gather_facts: false
  vars:
    AdminUser: "{{hostvars['localhost']['influxUser']}}"
    AdminPass: "{{hostvars['localhost']['influxPass']}}"
    TelegrafUserPass: "{{hostvars['localhost']['telegrafPass']}}"
    GrafanaUserPass: "{{hostvars['localhost']['grafanaPass']}}"
  tasks:
    - include: monitor-setup.yml
