---
- name: Create aws ec2 nodejs server
  hosts: localhost
  become: false
  gather_facts: false
  vars_prompt:
    - name: "instanceName"
      prompt: "Enter the name for the instance"
      private: no
  vars:
    ec2size: t2.micro
  tasks:
    - include: ec2-instance-create.yml
  
- name: Setup nodejs
  hosts: instances
  become: false
  gather_facts: false
  tasks:
    - include: setup-nodejs.yml
    - include: setup-iptables.yml
