---
- name: Create aws ec2 nodejs server
  hosts: localhost
  become: false
  gather_facts: false
  vars_prompt:
    - name: "instanceName"
      prompt: "Enter the name for the instance"
      private: no
  vars:
    ec2size: t2.small
  tasks:
    - include: ec2-instance-create.yml

- name: Setup Redis
  hosts: instances
  become: false
  gather_facts: false
  tasks:
    - include: redis-setup.yml

- name: Check Redis Status
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Wait for Redis
      wait_for:
        host: "{{ item.private_dns_name }}"
        port: 6379
        delay: 60
        timeout: 320
        state: started
      with_items:
        - "{{ result.instances }}"
