---
- name: Discover instances(s)
  become: false
  gather_facts: false
  hosts: localhost
  vars_prompt:
    - name: "hostName"
      prompt: "Enter the name of the instance"
      private: no
  tasks:
    - include: ec2-instance-discover.yml

- name: Setup redis
  hosts: instances
  become: false
  gather_facts: false
  tasks:
    - include: redis-setup.yml

- name: Check Redis Status
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Wait for Redis
      wait_for:
        host: "{{ item.private_dns_name }}"
        port: 6379
        delay: 60
        timeout: 320
        state: started
      with_items:
        - "{{ result.instances }}"
